import type { SiteAdminConfig } from './config'
import { contentTableName, fieldStorage, validateContentNames } from './schema-model'
import { commonSchemaSource } from './schema-template'
import type { BetterAuthOptions } from 'better-auth'
import { admin } from 'better-auth/plugins'

type NativeAuthConfig =
    | BetterAuthOptions
    | ((context: { db: unknown; requestOrigin?: string; runtimeConfig: Record<string, unknown> }) => BetterAuthOptions)

/** Uses Better Auth's schema generator without initializing auth or connecting to a database. */
export async function generateCombinedSchema(config: SiteAdminConfig, auth: NativeAuthConfig): Promise<string> {
    const resolved = typeof auth === 'function' ? auth({ db: undefined, runtimeConfig: {} }) : auth
    if (typeof resolved.database !== 'function')
        throw new Error(
            'Auth generation requires the application-selected native adapter factory with createSchema. Defer opening its database during schema inspection.',
        )
    const plugins = [...(resolved.plugins ?? [])]
    if (!plugins.some((plugin) => plugin.id === 'admin')) plugins.push(admin())
    const authOptions: BetterAuthOptions = {
        ...resolved,
        plugins,
    }
    const adapter = resolved.database(authOptions)
    if (!adapter.createSchema)
        throw new Error('The application-selected native auth adapter does not implement createSchema.')
    const { getAuthTables } = await import('better-auth/db')
    const generated = await adapter.createSchema({ tables: getAuthTables(authOptions), file: 'schema.ts' })
    if (!generated?.code) throw new Error('Better Auth returned no schema source.')
    return mergeSchemaSources(generateSiteAdminSchema(config), generated.code)
}

// Both generators emit named imports. Reject unsupported syntax rather than silently producing a broken schema.
function mergeSchemaSources(...sources: string[]): string {
    const imports = new Map<string, Set<string>>()
    const exports = new Set<string>()
    const tables = new Set<string>()
    const bodies = sources.map((source) => {
        for (const match of source.matchAll(/sqliteTable\(\s*['"]([^'"]+)['"]/g)) {
            const name = match[1]!.toLowerCase()
            if (tables.has(name)) throw new Error(`Duplicate schema table: ${name}`)
            tables.add(name)
        }
        for (const match of source.matchAll(/export const (\w+)/g)) {
            if (exports.has(match[1]!)) throw new Error(`Duplicate schema export: ${match[1]}`)
            exports.add(match[1]!)
        }
        const body = source.replace(
            /import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"];?/g,
            (_, names: string, module: string) => {
                if (!['drizzle-orm', 'drizzle-orm/sqlite-core'].includes(module))
                    throw new Error('Combined schema generation supports Drizzle SQLite only.')
                const bindings = imports.get(module) ?? new Set<string>()
                for (const name of names
                    .split(',')
                    .map((binding) => binding.trim())
                    .filter(Boolean))
                    bindings.add(name)
                imports.set(module, bindings)
                return ''
            },
        )
        if (/^\s*import\s/m.test(body)) throw new Error('Unsupported schema import syntax.')
        return body.trim()
    })
    return (
        [...imports]
            .map(([module, names]) => `import { ${[...names].join(', ')} } from ${JSON.stringify(module)}`)
            .join('\n') +
        '\n\n' +
        bodies.join('\n\n') +
        '\n'
    )
}

/** Pure code generation: no database connection or migration application. */
export const generateSiteAdminSchema = (config: SiteAdminConfig): string => {
    validateContentNames(config)
    const result = ['// Generated by Site Admin. Edit site-admin.config.ts, then regenerate.', commonSchemaSource]
    for (const [name, model] of Object.entries(config.models)) {
        const columns = Object.entries(model.fields).map(([key, field]) => {
            const type = fieldStorage(field),
                column = JSON.stringify(`field_${key}`)
            const builder =
                type === 'json'
                    ? `text(${column}, { mode: 'json' })`
                    : type === 'boolean'
                      ? `integer(${column}, { mode: 'boolean' })`
                      : `${type}(${column})`
            return `${JSON.stringify(key)}: ${builder}${field.required ? '.notNull()' : ''}`
        })
        const identifier = `content_${Buffer.from(name).toString('hex')}`
        result.push(
            `export const ${identifier} = sqliteTable(${JSON.stringify(contentTableName(name))}, {\n  revisionId: text('revision_id').primaryKey().references(() => revisions.id, { onDelete: 'cascade' }),\n  ${columns.join(',\n  ')}\n})`,
        )
    }
    return result.join('\n') + '\n'
}
