import { defineConfig } from 'tsdown'

export default defineConfig({
    attw: { level: 'error', profile: 'esm-only' },
    clean: true,
    copy: [{ from: '../../README.md', to: '.' }],
    deps: {
        dts: { neverBundle: true },
        neverBundle: true,
        onlyImport: [
            '@nuxt/kit',
            '@standard-schema/spec',
            '@tanstack/vue-form',
            'comark',
            'comark-content',
            'db0',
            'files-sdk',
            'h3',
            'jiti',
            'nuxt-files-sdk',
            'node:path',
            'rou3',
            'vue',
        ],
    },
    dts: true,
    entry: {
        ai: 'src/ai.ts',
        form: 'src/form.ts',
        index: 'src/index.ts',
        nuxt: 'src/nuxt.ts',
        'runtime/diagnostics-handler': 'src/runtime/diagnostics-handler.ts',
        'runtime/llms-handler': 'src/runtime/llms-handler.ts',
        server: 'src/server/index.ts',
        'runtime/management-handler': 'src/runtime/management-handler.ts',
        'runtime/public-handler': 'src/runtime/public-handler.ts',
    },
    exports: false,
    format: ['esm'],
    platform: 'neutral',
    publint: true,
    sourcemap: true,
    unbundle: true,
})
